title: "client_side_ai_training"
description: "A Browser-Based AI Training Playground"
baseurl: "/client_side_ai_training"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge